spring:
  jpa:
    #show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true

  datasource:
    url: jdbc:mariadb://localhost:3306/together
    driver-class-name: org.mariadb.jdbc.Driver
    username: together_admin
    password: root

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace